#!/bin/sh

case $1 in
  dev) node app.js development ;;
  lint) eslint --config ../.eslintrc.json --fix "root/**/*.js" ;;
  slint) stylelint --config ../.stylelintrc.json --fix "root/**/*.css" ;;

  opm) ../media-optimizer.sh root/media ;;

  prod) time node app.js production ;;

  *) echo "Invalid task $1" >&2; exit 1 ;;
esac
